name: Scrape Duolingo Data

on:
  schedule:
    - cron: '0 6 * * *' 
  workflow_dispatch:  

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache Python dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set up ChromeDriver
        run: |
          wget https://chromedriver.storage.googleapis.com/111.0.5563.64/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          mv chromedriver /usr/local/bin/

      - name: Run Scraper Script
        env:
          DUOLINGO_EMAIL: ${{ secrets.DUOLINGO_EMAIL }}
          DUOLINGO_PASSWORD: ${{ secrets.DUOLINGO_PASSWORD }}
        run: |
          python chrome.py
